stages:
  split:
    cmd: python -m src.data.data_split
    deps:
    - data/raw_data/raw.csv
    - src/data/data_split.py
    - src/data/check_structure.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python -m src.data.normalize
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - src/data/check_structure.py
    - src/data/normalize.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python -m src.models.grid_search
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python -m src.models.training
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/training.py
    outs:
    - models/trained_model.pkl
  evaluate:
    cmd: python -m src.models.evaluate
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/trained_model.pkl
    - src/models/evaluate.py
    - src/data/check_structure.py
    outs:
    - metrics/scores.json
    - data/processed_data/predictions.csv